<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_minPrice</name>
   <tag></tag>
   <elementGuidId>2f392cd8-1c78-4761-a383-e004a8138d38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='pmin']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@data-testid = 'iptSRPMinPriceFilter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;pmin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0ddad49-f062-4e00-b949-2ec268491570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-unify</name>
      <type>Main</type>
      <value>TextField</value>
      <webElementGuid>5846229c-99b8-43df-bf64-1d9767ddcba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pmin</value>
      <webElementGuid>6d1b2a3b-b544-4df5-9256-681c8def2aa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Harga Minimum</value>
      <webElementGuid>c78a7fbe-858b-4408-8acb-c31a63396c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>682b1993-4067-4faa-8622-6e2025480190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>iptSRPMinPriceFilter</value>
      <webElementGuid>e2013fae-050d-4cf0-b9f9-427c07e63119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-3017qm exxxdg63</value>
      <webElementGuid>cd4210e0-393f-48f9-88d5-994a8b374568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-gfb3wv&quot;]/div[@class=&quot;css-18nstr8&quot;]/div[1]/div[@class=&quot;css-khi8sg&quot;]/div[1]/div[@class=&quot;css-1ghv7i5&quot;]/div[@class=&quot;css-1m93f3h&quot;]/div[1]/div[@class=&quot;css-1cb34wj&quot;]/div[@class=&quot;css-frokek&quot;]/div[@class=&quot;css-d145w4 erj7th70&quot;]/div[@class=&quot;css-79elbk erj7th72&quot;]/div[@class=&quot;css-ufaufa erj7th73&quot;]/input[@class=&quot;css-3017qm exxxdg63&quot;]</value>
      <webElementGuid>4e75b331-1a26-45e7-b435-f8ace66c2a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='pmin']</value>
      <webElementGuid>49588960-a083-420f-9b18-03f16afa7a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div/div/div/div/div/div[4]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>bd8db6a8-a200-4e1e-b8d0-64e020eda894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div/div/div/div/input</value>
      <webElementGuid>75648067-a7bc-4a80-9a5d-8bfbaf4dd185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'pmin' and @placeholder = 'Harga Minimum' and @type = 'text']</value>
      <webElementGuid>a9e16d8d-dbd5-4145-85f1-d531eda9ae34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
