<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>searchResultHeader</name>
   <tag></tag>
   <elementGuidId>80803142-cb20-4aa2-9696-4ecfa9256226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-testid = 'result-header-wrapper']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.css-k1aaub</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0ddb62a7-55d0-4213-a08f-2b300495f3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-k1aaub</value>
      <webElementGuid>1313446f-633d-4937-a73f-0da7e296376d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>result-header-wrapper</value>
      <webElementGuid>5393f280-abfc-42e7-984d-19c909435519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ssr</name>
      <type>Main</type>
      <value>resultHeaderSRPSSR</value>
      <webElementGuid>2e3c5f4d-0ab0-44e8-8bc1-d157a464d6df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Menampilkan 1 - 60 barang dari total 14rb+ untuk &quot;asd&quot;Urutkan:Paling Sesuai</value>
      <webElementGuid>b20e8df6-35aa-4e97-aaa4-1c259601e7f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zeus-root&quot;)/div[@class=&quot;css-8atqhb&quot;]/div[@class=&quot;css-jau1bt&quot;]/div[@class=&quot;css-1c82svt&quot;]/div[@class=&quot;css-rjanld&quot;]/div[@class=&quot;css-k1aaub&quot;]</value>
      <webElementGuid>a503dada-eea0-472b-b3cd-89761575b848</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zeus-root']/div/div[2]/div/div[2]/div[2]</value>
      <webElementGuid>7b5ec267-1ac9-4820-9c3a-1ca9d6233e14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko'])[1]/following::div[1]</value>
      <webElementGuid>fe1e6c17-8961-4920-a693-526fc507c8e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Produk'])[1]/following::div[1]</value>
      <webElementGuid>75d519fd-739a-4da8-b08d-aceb546f23d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]</value>
      <webElementGuid>fb83e98a-e82e-4dae-b452-39676cb6a26c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Menampilkan 1 - 60 barang dari total 14rb+ untuk &quot;asd&quot;Urutkan:Paling Sesuai' or . = 'Menampilkan 1 - 60 barang dari total 14rb+ untuk &quot;asd&quot;Urutkan:Paling Sesuai')]</value>
      <webElementGuid>37893652-81ed-4127-afe3-9b7bf97cf0d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
